version: '3'
services:
  epidocs:
    container_name: epidocs
    image: musubi42/epidocs:v0.0.7
    ports:
      - 4200:3000
    # volumes:
      # - .:/home/node/app/
    restart: unless-stopped
    networks:
      - npm_network

networks:
  npm_network:
    driver: bridge
