version: '3'
services:
  epidocs:
    image: musubi42/epidocs:v0.0.1
    ports:
      - "3042:3042"
    volumes:
      - /opt/portainer/Epitech/EpiDocs:/home/node/app/
    restart: unless-stopped
    networks:
      - npm_network

networks:
  npm_network:
    driver: bridge